### ISSUE TITLE
ThemeSelectDropdowns_Size_CutsOff

### ISSUE THREAD

**Issue by Lomzy66** [dsandstrom/atom-afterglow-ui#4]
**Disclaimer:** My current monitor is kind of oddly sized but the picture below is reproduced on a few other resolutions as well as a 15" HP laptop screen.

![atomafterglow_ui_issue](https://user-images.githubusercontent.com/20676528/36378495-ad3ffa5e-1583-11e8-975b-3c472aa7bdda.JPG)

**Comment by dsandstrom** [comment]
I think this is fixed, but I'm unable to deploy another release.  Something related to: https://github.com/atom/apm/issues/315 .  You'll have to clone the repo and use `apm link` to see the changes for now.

**Comment by Lomzy66** [comment]
Hey dsandstrom yes it's fixed. Thanks a ton!

I just cloned and then copied the files to overwrite the old version and it worked like a charm.

**Comment by dsandstrom** [comment]
Alright, figured out the issue and was able to publish.  Fixed in v0.22.0.
